"""Add flat relationship to MaintenanceBill

Revision ID: 2165ceb62892
Revises: e7139b7a66a2
Create Date: 2025-08-05 21:30:29.788121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2165ceb62892'
down_revision = 'e7139b7a66a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('vendor',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('approval_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_status', sa.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('vendor',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
