"""Add email column to flats table

Revision ID: 265bb14c57bd
Revises: 3fadcfaa7874
Create Date: 2025-08-03 18:57:06.730982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '265bb14c57bd'
down_revision = '3fadcfaa7874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flats', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
