"""change expense table

Revision ID: 2d79c974ba4a
Revises: 1d1762470dfe
Create Date: 2025-09-30 08:21:22.673346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d79c974ba4a'
down_revision = '1d1762470dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('expenses_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('description')
        batch_op.drop_column('flat_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flat_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', mysql.TEXT(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('expenses_ibfk_1'), 'flats', ['flat_id'], ['flat_id'], ondelete='CASCADE')

    # ### end Alembic commands ###
