"""Initial migration

Revision ID: 408a07444c8b
Revises: 
Create Date: 2025-08-09 10:40:40.571820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408a07444c8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_budgets',
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('monthly_limit', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('category')
    )
    op.create_table('financial_reports',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=True),
    sa.Column('opening_balance', sa.Float(), nullable=True),
    sa.Column('total_income', sa.Float(), nullable=True),
    sa.Column('total_expenses', sa.Float(), nullable=True),
    sa.Column('closing_balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('flats',
    sa.Column('flat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flat_number', sa.String(length=10), nullable=False),
    sa.Column('owner_name', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('maintenance_status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('flat_id'),
    sa.UniqueConstraint('flat_number')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('recipient', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('expenses',
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('flat_id', sa.Integer(), nullable=True),
    sa.Column('vendor', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('receipt_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['flat_id'], ['flats.flat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('expense_id')
    )
    op.create_table('maintenance_bills',
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('flat_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('base_amount', sa.Float(), nullable=False),
    sa.Column('late_fee', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['flat_id'], ['flats.flat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bill_id')
    )
    op.create_table('payment',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.Column('receipt_number', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['maintenance_bills.bill_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('maintenance_bills')
    op.drop_table('expenses')
    op.drop_table('users')
    op.drop_table('notification')
    op.drop_table('flats')
    op.drop_table('financial_reports')
    op.drop_table('category_budgets')
    # ### end Alembic commands ###
