"""Add maintenance_status to flats

Revision ID: 5850f8409b6b
Revises: 265bb14c57bd
Create Date: 2025-08-04 18:48:08.968694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5850f8409b6b'
down_revision = '265bb14c57bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maintenance_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flats', schema=None) as batch_op:
        batch_op.drop_column('maintenance_status')

    # ### end Alembic commands ###
