"""send mail

Revision ID: 5e356b77e368
Revises: a9b854783371
Create Date: 2025-10-15 21:15:45.861609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e356b77e368'
down_revision = 'a9b854783371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('tennant_email', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flats', schema=None) as batch_op:
        batch_op.drop_column('tennant_email')
        batch_op.drop_column('owner_email')

    # ### end Alembic commands ###
