"""handling delete anomaly

Revision ID: 5f387eacb362
Revises: 5e356b77e368
Create Date: 2026-01-03 15:46:39.191966

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f387eacb362'
down_revision = '5e356b77e368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_budgets')
    op.drop_table('credits')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('expenses_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'flats', ['flat_id'], ['flat_id'])

    with op.batch_alter_table('flats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('maintenance_bills', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('maintenance_bills_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'flats', ['flat_id'], ['flat_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_bills', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('maintenance_bills_ibfk_1'), 'flats', ['flat_id'], ['flat_id'], ondelete='CASCADE')

    with op.batch_alter_table('flats', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('expenses_ibfk_1'), 'flats', ['flat_id'], ['flat_id'], ondelete='CASCADE')

    op.create_table('credits',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('flat_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('reason', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('used', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['flat_id'], ['flats.flat_id'], name=op.f('credits_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('category_budgets',
    sa.Column('category', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('monthly_limit', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('category'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
