"""Add Payment model

Revision ID: 68e38a266e52
Revises: 2165ceb62892
Create Date: 2025-08-05 21:55:12.835438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e38a266e52'
down_revision = '2165ceb62892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.Column('receipt_number', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['maintenance_bills.bill_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.drop_table('payments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('payment_id', sa.INTEGER(), nullable=False),
    sa.Column('bill_id', sa.INTEGER(), nullable=False),
    sa.Column('payment_date', sa.DATETIME(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('mode', sa.VARCHAR(length=20), nullable=True),
    sa.Column('receipt_url', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['maintenance_bills.bill_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.drop_table('payment')
    # ### end Alembic commands ###
