"""add performance indexes

Revision ID: 7fb37e5be158
Revises: f3cdf95d065b
Create Date: 2026-02-08 10:39:41.211398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fb37e5be158'
down_revision = 'f3cdf95d065b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advance_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advance_payments_flat_id'), ['flat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_advance_payments_payment_date'), ['payment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_advance_payments_start_month'), ['start_month'], unique=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_flat_id'), ['flat_id'], unique=False)

    with op.batch_alter_table('flats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('flat_number'))
        batch_op.create_index(batch_op.f('ix_flats_flat_number'), ['flat_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_flats_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('maintenance_bills', schema=None) as batch_op:
        batch_op.create_index('idx-flat_month', ['flat_id', 'month'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_bills_flat_id'), ['flat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_bills_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_bills_status'), ['status'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('username'))
        batch_op.create_index(batch_op.f('ix_users_flat_id'), ['flat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_flat_id'))
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)

    with op.batch_alter_table('maintenance_bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_bills_status'))
        batch_op.drop_index(batch_op.f('ix_maintenance_bills_month'))
        batch_op.drop_index(batch_op.f('ix_maintenance_bills_flat_id'))
        batch_op.drop_index('idx-flat_month')

    with op.batch_alter_table('flats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flats_is_active'))
        batch_op.drop_index(batch_op.f('ix_flats_flat_number'))
        batch_op.create_index(batch_op.f('flat_number'), ['flat_number'], unique=True)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_flat_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_date'))
        batch_op.drop_index(batch_op.f('ix_expenses_category'))

    with op.batch_alter_table('advance_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advance_payments_start_month'))
        batch_op.drop_index(batch_op.f('ix_advance_payments_payment_date'))
        batch_op.drop_index(batch_op.f('ix_advance_payments_flat_id'))

    # ### end Alembic commands ###
