"""change expense

Revision ID: a9b854783371
Revises: 2d79c974ba4a
Create Date: 2025-09-30 08:23:22.516216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b854783371'
down_revision = '2d79c974ba4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flat_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'flats', ['flat_id'], ['flat_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('flat_id')

    # ### end Alembic commands ###
