"""Fix flat_id autoincrement

Revision ID: e7139b7a66a2
Revises: 5850f8409b6b
Create Date: 2025-08-04 20:28:39.357237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7139b7a66a2'
down_revision = '5850f8409b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flats', schema=None) as batch_op:
        batch_op.alter_column('contact',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('maintenance_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('parking_slot')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parking_slot', sa.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('maintenance_status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('contact',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
