"""map user to flat

Revision ID: f3cdf95d065b
Revises: dc5bdb6f9f8b
Create Date: 2026-01-11 17:59:59.149443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3cdf95d065b'
down_revision = 'dc5bdb6f9f8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flat_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'flats', ['flat_id'], ['flat_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('flat_id')

    # ### end Alembic commands ###
